import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import calendar
data=pd.read_csv("D:/Customer Loyalty History.csv")
print(data)
print("Dataset Info",data.info)
print(data.isnull().sum())
#fill value with mean (salary column)
x=data['Salary'].mean()
print(x)
data['Salary']=data['Salary'].fillna(x)
print(data['Salary'])
#fill value with meadian (cancellation year column)
y=data['Cancellation Year'].median()
print(y)
data['Cancellation Year']=data['Cancellation Year'].fillna(y)
print(data['Cancellation Year'])
#fill value with meadian (cancellation month column)
z=data['Cancellation Month'].median()
print(z)
data['Cancellation Month']=data['Cancellation Month'].fillna(z)
print(data['Cancellation Month'])
print(data)
print(data.describe())
#education vs gender
sns.countplot(data=data,x='Education',hue='Gender')
plt.title("Education vs Gender")
plt.show()
#gender distribution
gender_count=data['Gender'].value_counts()
plt.pie(gender_count,labels=gender_count.index,autopct='%1.1f%%',startangle=90,colors=['skyblue','hotpink'])
plt.title("Gender Distribution")
plt.show()
#salary distribution
sns.histplot(data['Salary'],bins=20,kde=True)
plt.show()
#city vs gender
plt.figure(figsize=(10,10))
sns.countplot(data=data,x='City',hue='Gender',order=data['City'].value_counts().index[:10])
plt.title("Gender Distribution by City(Top 10 Cities)")
plt.show()
#clv distribution
sns.kdeplot(data['CLV'],color='blue')
plt.title("CLV Distribution")
plt.show()
#enrollmentyear vs gender
enrollmentyear_count = data.groupby(['Enrollment Year', 'Gender']).size().reset_index(name='count')
plt.figure(figsize=(10, 6))
sns.lineplot(data=enrollmentyear_count, x='Enrollment Year', y='count', hue='Gender', marker="o")
plt.title('Enrollment Year Count by Gender')
plt.xlabel('Enrollment Year')
plt.ylabel('Number of Persons')
plt.grid(True)
plt.show()
#cancellationyear vs gender
cancellationyear_count=data.groupby(['Cancellation Year','Gender']).size().reset_index(name='count')
plt.figure(figsize=(10,6))
sns.lineplot(data=cancellationyear_count,x='Cancellation Year',y='count',hue='Gender',marker="o")
plt.title('Cancellation Year Count by Gender')
plt.xlabel('Cancellation Year')
plt.ylabel('Number of Persons')
plt.grid(True)
plt.show()
#new column add enrollment month name(number to month)
data['Enrollment Month Name']=data['Enrollment Month'].apply(lambda x:calendar.month_name[int(x)])
print(data[['Enrollment Month','Enrollment Month Name']])
#new column add cancellation month name(number to month)
data['Cancellation Month Name']=data['Cancellation Month'].apply(lambda x:calendar.month_name[int(x)])
print(data[['Cancellation Month','Cancellation Month Name']])
#enrollment count with year and month
pivot = data.groupby(['Enrollment Year', 'Enrollment Month']).size().unstack().fillna(0)
sns.heatmap(pivot, annot=True, fmt=".0f", cmap="YlGnBu")
plt.title('Enrollments Heatmap (Year vs Month)')
plt.xlabel('Month')
plt.ylabel('Year')
plt.show()
data.to_csv("cleaned_customer_loyalty_history.csv")

